package javaapplication33;

import com.GUI.Fonts.FontManager;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import com.k33ptoo.components.KButton;
import java.awt.Color;
import javax.swing.BorderFactory;

public final class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     *
     * @throws java.awt.FontFormatException
     * @throws java.io.IOException
     */
    public LoginForm() throws FontFormatException, IOException {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        picFeaturesBG = new javax.swing.JLabel();
        pnlLoginFields = new javax.swing.JPanel();
        picColorIcon = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kBtnLoginPrompt = new com.k33ptoo.components.KButton();
        lblTagline2 = new javax.swing.JLabel();
        lblTagline1 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        picBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ShadiFinTech Banking System");
        setIconImage(new ImageIcon(getClass().getResource("/com/images/FrameIcon.png")).getImage());
        setLocation(new java.awt.Point(500, 180));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        picFeaturesBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/FeaturesBG.png"))); // NOI18N
        picFeaturesBG.setVisible(false);
        getContentPane().add(picFeaturesBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, -1, -1));

        pnlLoginFields.setBackground(new java.awt.Color(242, 242, 242));
        pnlLoginFields.setVisible(false);
        pnlLoginFields.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        picColorIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/ColorLogo.png"))); // NOI18N
        pnlLoginFields.add(picColorIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        lblLogin.setFont(new Font(loadFonts(0).getFontName(),Font.BOLD,55));
        lblLogin.setForeground(new java.awt.Color(16, 20, 20));
        lblLogin.setText("Login");
        pnlLoginFields.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 280, 90));

        getContentPane().add(pnlLoginFields, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 720));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/WhiteLogo.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        kBtnLoginPrompt.setBorder(null);
        kBtnLoginPrompt.setForeground(new java.awt.Color(51, 57, 140));
        kBtnLoginPrompt.setText("Log In");
        kBtnLoginPrompt.setFont(new Font(loadFonts(9).getFontName(),Font.BOLD,30));
        kBtnLoginPrompt.setkBackGroundColor(new java.awt.Color(242, 242, 242));
        kBtnLoginPrompt.setkEndColor(new java.awt.Color(242, 242, 242));
        kBtnLoginPrompt.setkForeGround(new java.awt.Color(51, 57, 140));
        kBtnLoginPrompt.setkHoverEndColor(new java.awt.Color(51, 57, 140));
        kBtnLoginPrompt.setkHoverForeGround(new java.awt.Color(242, 242, 242));
        kBtnLoginPrompt.setkHoverStartColor(new java.awt.Color(0, 0, 51));
        kBtnLoginPrompt.setkStartColor(new java.awt.Color(255, 255, 255));
        kBtnLoginPrompt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kBtnLoginPromptActionPerformed(evt);
            }
        });
        getContentPane().add(kBtnLoginPrompt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 485, 190, 60));

        lblTagline2.setFont(new Font(loadFonts(0).getFontName(),Font.BOLD,75));
        lblTagline2.setForeground(new java.awt.Color(242, 242, 242));
        lblTagline2.setText("Seamless Experience.");
        getContentPane().add(lblTagline2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 820, 80));

        lblTagline1.setFont(new Font(loadFonts(0).getFontName(),Font.BOLD,75));
        lblTagline1.setForeground(new java.awt.Color(242, 242, 242));
        lblTagline1.setText("Secure Banking,");
        getContentPane().add(lblTagline1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 850, 90));

        lblTitle.setFont(new Font(loadFonts(0).getFontName(),Font.BOLD,25));
        lblTitle.setForeground(new java.awt.Color(242, 242, 242));
        lblTitle.setText("ShadiFinTech");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 510, 40));

        picBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/Background.png"))); // NOI18N
        getContentPane().add(picBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kBtnLoginPromptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kBtnLoginPromptActionPerformed
        lblTagline1.setVisible(false);
        lblTagline2.setVisible(false);
        
        picBG.setVisible(false);
        picFeaturesBG.setVisible(true);
        pnlLoginFields.setVisible(true);
        
    }//GEN-LAST:event_kBtnLoginPromptActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new LoginForm().setVisible(true);
            } catch (FontFormatException | IOException ex) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private com.k33ptoo.components.KButton kBtnLoginPrompt;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblTagline1;
    private javax.swing.JLabel lblTagline2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel picBG;
    private javax.swing.JLabel picColorIcon;
    private javax.swing.JLabel picFeaturesBG;
    private javax.swing.JPanel pnlLoginFields;
    // End of variables declaration//GEN-END:variables

    public Font loadFonts(int i) {
        FontManager fontManager = new FontManager();

        // Set the desired font for lblTitle
        return fontManager.registerFonts(i);
    }
}
