package javaapplication33;

import com.GUI.Fonts.FontManager;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author User's
 */
public class LoginForm extends javax.swing.JFrame {
    
    Font fontTitle;
    
    /**
     * Creates new form LoginForm
     * @throws java.awt.FontFormatException
     * @throws java.io.IOException
     */
    public LoginForm() throws FontFormatException, IOException {
        this.fontTitle = Font.createFont(Font.BOLD, new File(loadFonts(3)));
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ShadiFinTech Banking System");
        setIconImage(new ImageIcon(getClass().getResource("/com/images/FrameIcon.png")).getImage());
        setLocation(new java.awt.Point(500, 180));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(fontTitle);
        lblTitle.setForeground(new java.awt.Color(242, 242, 242));
        lblTitle.setText("ShadiFinTech");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 500, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/WhiteLogo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/LoginBG.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new LoginForm().setVisible(true);
            } catch (FontFormatException | IOException ex) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

    private String loadFonts(int i) {
        String[] fontPaths = {
            "C:\\Users\\User's\\Documents\\NetBeansProjects\\JavaApplication33\\src\\com\\GUI\\Fonts\\QuinoaUltrabold_2.otf",
            "C:\\Users\\User's\\Documents\\NetBeansProjects\\JavaApplication33\\src\\com\\GUI\\Fonts\\QuinoaBlack.otf",
            "C:\\Users\\User's\\Documents\\NetBeansProjects\\JavaApplication33\\src\\com\\GUI\\Fonts\\QuinoaBlackItalics.otf",
            "C:\\Users\\User's\\Documents\\NetBeansProjects\\JavaApplication33\\src\\com\\GUI\\Fonts\\QuinoaBold.otf",
            "C:\\Users\\User's\\Documents\\NetBeansProjects\\JavaApplication33\\src\\com\\GUI\\Fonts\\QuinoaBoldItalics.otf",
            "C:\\Users\\User's\\Documents\\NetBeansProjects\\JavaApplication33\\src\\com\\GUI\\Fonts\\QuinoaHeavy.otf",
            "C:\\Users\\User's\\Documents\\NetBeansProjects\\JavaApplication33\\src\\com\\GUI\\Fonts\\QuinoaHeavyItalics.otf",
            "C:\\Users\\User's\\Documents\\NetBeansProjects\\JavaApplication33\\src\\com\\GUI\\Fonts\\QuinoaLight.otf",
            "C:\\Users\\User's\\Documents\\NetBeansProjects\\JavaApplication33\\src\\com\\GUI\\Fonts\\QuinoaLightItalics.otf",
            "C:\\Users\\User's\\Documents\\NetBeansProjects\\JavaApplication33\\src\\com\\GUI\\Fonts\\QuinoaMedium.otf",
            "C:\\Users\\User's\\Documents\\NetBeansProjects\\JavaApplication33\\src\\com\\GUI\\Fonts\\QuinoaMediumItalics.otf",
            "C:\\Users\\User's\\Documents\\NetBeansProjects\\JavaApplication33\\src\\com\\GUI\\Fonts\\QuinoaRegular.otf",
            "C:\\Users\\User's\\Documents\\NetBeansProjects\\JavaApplication33\\src\\com\\GUI\\Fonts\\QuinoaRegularItalics.otf",
            "C:\\Users\\User's\\Documents\\NetBeansProjects\\JavaApplication33\\src\\com\\GUI\\Fonts\\QuinoaSemibold.otf",
            "C:\\Users\\User's\\Documents\\NetBeansProjects\\JavaApplication33\\src\\com\\GUI\\Fonts\\QuinoaSemiboldItalics.otf",
            "C:\\Users\\User's\\Documents\\NetBeansProjects\\JavaApplication33\\src\\com\\GUI\\Fonts\\QuinoaThin.otf",
            "C:\\Users\\User's\\Documents\\NetBeansProjects\\JavaApplication33\\src\\com\\GUI\\Fonts\\QuinoaThinItalics.otf",
            "C:\\Users\\User's\\Documents\\NetBeansProjects\\JavaApplication33\\src\\com\\GUI\\Fonts\\QuinoaUltrabold.otf",
            "C:\\Users\\User's\\Documents\\NetBeansProjects\\JavaApplication33\\src\\com\\GUI\\Fonts\\QuinoaUltraboldItalics.otf"
        };
        
        FontManager.loadFont(fontPaths, 15f);
        
        return fontPaths [i];
    }
}
